# Generated by Django 3.2.5 on 2021-07-20 08:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('collage_app', '0002_auto_20210719_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='serie',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='uploads/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tokenimage',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tokenimage',
            name='image',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
