# Generated by Django 3.2.5 on 2021-07-20 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collage_app', '0003_auto_20210720_0834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tokenimage',
            old_name='number',
            new_name='title',
        ),
    ]
