# Generated by Django 3.2.5 on 2021-07-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collage_app', '0005_rename_title_tokenimage_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
    ]
