# Generated by Django 3.2.5 on 2021-07-29 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collage_app', '0006_alter_serie_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TokenImage',
            new_name='Token',
        ),
        migrations.RemoveField(
            model_name='serie',
            name='license_name',
        ),
        migrations.RemoveField(
            model_name='serie',
            name='total_minted',
        ),
    ]
