# Generated by Django 3.2.5 on 2021-07-29 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collage_app', '0008_remove_token_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='description',
            new_name='title',
        ),
    ]
