# Generated by Django 3.2.5 on 2021-08-16 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collage_app', '0009_rename_description_token_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
