# Generated by Django 3.2.5 on 2021-08-20 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collage_app', '0010_alter_serie_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='serie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='collage_app.serie'),
        ),
    ]
