# Generated by Django 3.2.5 on 2021-08-20 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collage_app', '0011_alter_token_serie'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='choices',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('SOLD', 'Sold')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
